创建文件夹、创建文件、操作文件

In [ ]:
import os

os.makedirs(os.path.join('data'), exist_ok=True)
data_file = os.path.join('data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

读取文件

In [ ]:
# 如果没有安装pandas，只需取消对以下行的注释来安装pandas
# !pip install pandas
import pandas as pd

data = pd.read_csv(data_file)
print(data)

插值

In [ ]:
# 有bug，字符串类型不能用mean取平均值
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

In [ ]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
print(inputs)

pandas的data不能直接以数组的取值方法获取值，而是需要iloc(index_location)

In [ ]:
print(inputs.iloc[:, 0])

In [ ]:
inputs.iloc[:,0] = inputs.iloc[:,0].fillna(inputs.iloc[:,0].mean())
print(inputs)

字符串对应列变为两列，两个特征

In [ ]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

如果三个特征呢

In [ ]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs.iloc[1,1]="prepare"
print(inputs)

In [ ]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

tpandas数据DataFrame   转换为torch的张量tensor

In [ ]:
import torch

# inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
# inputs.iloc[:,0] = inputs.iloc[:,0].fillna(inputs.iloc[:,0].mean())
# inputs = pd.get_dummies(inputs, dummy_na=True)

# print("type(inputs)\n",type(inputs))
# print("inputs\n",inputs)
# print("inputs.values\n",inputs.values)
# print("inputs.values.dtype\n",inputs.values.dtype) # object
# print("type(inputs.values)\n",type(inputs.values))  # <class 'numpy.ndarray'>
# print("inputs.to_numpy()\n",inputs.to_numpy())
# print("type(inputs.to_numpy())\n",type(inputs.to_numpy()))  # <class 'numpy.ndarray'>
# print("type(inputs.to_numpy(dtype=float))\n",type(inputs.to_numpy(dtype=float)))

# X,y=torch.tensor(inputs.values,dtype=torch.float32),torch.tensor(outputs.values,dtype=torch.float32) #为什么不能这样转? bool和int混合成object无法转
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

In [ ]:
print(type(X))

——

——


奇怪现象：
通过reshape创造的变量，在改动之后原来的变量也会跟着改变


In [ ]:
a=torch.arange(12).reshape(3,4)
a

In [ ]:
b=a
b

In [ ]:
b[:]=2
print(b)
print(a)

In [ ]:
print(b.shape)

通过clone可以开辟新内存

In [80]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
print(A)
print(B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


In [ ]:
A[:]=2
print(A)
print(B)

In [81]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])